log_format   cloudflare '$remote_addr - $remote_user [$time_local] "$request" $status $body_bytes_sent "$http_referer" "$http_user_agent" $http_cf_ray $http_cf_connecting_ip $http_x_forwarded_for $http_x_forwarded_proto $http_true_client_ip $http_cf_ipcountry $http_cf_visitor';
server {
      listen 80;
      # gzip config
      gzip on;
      gzip_min_length 1k;
      gzip_comp_level 9;
      gzip_types text/plain text/css text/javascript application/json application/javascript application/x-javascript application/xml;
      gzip_vary on;
      gzip_disable "MSIE [1-6]\.";

      root /usr/share/nginx/html;
      include /etc/nginx/mime.types;
      access_log  /var/log/nginx/example.com.access.log cloudflare;

      location / {
          add_header Cache-Control "private, no-store, no-cache, must-revalidate, proxy-revalidate";
          try_files $uri $uri/ /index.html;
      }

}
