package com.beukay.marketing.person.infrastructure.composition.render;

import com.beukay.marketing.person.domain.composition.model.ChapterPlan;
import com.beukay.marketing.person.domain.composition.model.ClipPick;
import com.beukay.marketing.person.domain.composition.model.CompositionPlan;
import lombok.RequiredArgsConstructor;
import lombok.extern.log4j.Log4j2;
import org.springframework.stereotype.Component;

import java.io.IOException;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardCopyOption;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.HashSet;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.Set;
import java.util.UUID;

/**
 * DaVinci Resolve 自动剪辑脚本生成器（参考 AutoCutVideo 的 utils.lua + split_narration.lua）。
 *
 * 输出目录：
 *   <name>/
 *     main.lua          ← 用户在 Resolve Console 用 dofile('/abs/main.lua') 调用
 *     command.txt       ← 一行 dofile 命令，方便复制
 *     Resources/        ← 自包含素材副本（视频/配音/BGM）
 *
 * Lua 脚本：
 *   1. 找到 Resolve 句柄（兼容 Console / fusion 两种执行环境）
 *   2. 设置项目分辨率/帧率
 *   3. ImportMedia 把 Resources/ 下所有素材入媒体池
 *   4. CreateEmptyTimeline + AppendToTimeline 把章节 picks 顺序拼到 V1，配音放到 A1（按章节起始位置 recordFrame），BGM 满轨放到 A2
 *   5. 若 autoRender=true，OpenPage('deliver') + LoadRenderPreset + AddRenderJob + StartRendering
 */
@Component
@RequiredArgsConstructor
@Log4j2
public class DavinciScriptWriter {

    public static final String EXPORT_TYPE_DIRECT = "DIRECT";
    public static final String EXPORT_TYPE_PREVIEW_EDIT = "PREVIEW_EDIT";

    public static class Args {
        public Path parentDir;
        public String name;
        public CompositionPlan plan;
        public int canvasW;
        public int canvasH;
        public int fps;
        public String codec;             // H264 / HEVC
        public String container;          // MP4 / MOV
        public String exportType;         // DIRECT / PREVIEW_EDIT
        public Map<String, Path> assetMap;
        public Path renderOutputDir;     // DaVinci 渲染产出位置
    }

    /** 写脚本目录，返回 main.lua 的绝对路径 */
    public Path writeScript(Args args) throws IOException {
        Path scriptDir = args.parentDir.resolve(sanitize(args.name));
        Files.createDirectories(scriptDir);

        // 拷贝素材到 Resources/，Lua 引用绝对路径，自包含
        Path resourcesDir = scriptDir.resolve("Resources");
        Files.createDirectories(resourcesDir);
        Map<String, String> friendlyNames = collectFriendlyNames(args.plan);
        Map<String, Path> resourceAssetMap = copyAssetsToResources(args.assetMap, resourcesDir, friendlyNames);

        // 拼 Lua 脚本
        String lua = buildLua(args, resourceAssetMap);
        Path mainLua = scriptDir.resolve("main.lua");
        Files.writeString(mainLua, lua);

        // dofile() 命令文本，便于复制
        Path command = scriptDir.resolve("command.txt");
        Files.writeString(command, "dofile('" + mainLua.toAbsolutePath() + "')\n");

        log.info("[davinci] wrote script {} (autoRender={}, {} clips, {} resources)",
                mainLua, EXPORT_TYPE_DIRECT.equalsIgnoreCase(args.exportType),
                countPicks(args.plan), resourceAssetMap.size());
        return mainLua;
    }

    // ─────────────────── Lua 生成 ───────────────────

    private String buildLua(Args args, Map<String, Path> resourceAssetMap) {
        boolean autoRender = EXPORT_TYPE_DIRECT.equalsIgnoreCase(args.exportType);
        int fps = args.fps;

        // 收集导入路径（去重，按 absolute）
        Set<String> uniquePaths = new java.util.LinkedHashSet<>();
        for (Path p : resourceAssetMap.values()) uniquePaths.add(p.toAbsolutePath().toString());

        StringBuilder sb = new StringBuilder();
        sb.append("-- DaVinci Resolve auto-edit script generated by marketing-person-center\n");
        sb.append("-- 用法：在 DaVinci Resolve Workspace → Console (或 Workspace → Scripts) 中执行\n");
        sb.append("--   dofile('").append(absLua(args)).append("')\n\n");

        // payload
        sb.append("local payload = ").append(luaTablePayload(args, resourceAssetMap, fps)).append("\n\n");

        // getResolve
        sb.append(LUA_GET_RESOLVE).append("\n");

        // 主体逻辑
        sb.append("local function run()\n");
        sb.append("    local resolve = getResolve()\n");
        sb.append("    if not resolve then\n");
        sb.append("        print('[davinci] Resolve not found')\n");
        sb.append("        diagnose()\n");
        sb.append("        return\n");
        sb.append("    end\n");
        sb.append("    local pm = resolve:GetProjectManager()\n");
        sb.append("    local project = pm:GetCurrentProject()\n");
        sb.append("    if not project then print('[davinci] no project open; please open or create a project first') return end\n\n");

        sb.append("    -- 项目分辨率 / 帧率\n");
        sb.append("    project:SetSetting('timelineResolutionWidth', tostring(payload.w))\n");
        sb.append("    project:SetSetting('timelineResolutionHeight', tostring(payload.h))\n");
        sb.append("    project:SetSetting('timelineOutputResolutionWidth', tostring(payload.w))\n");
        sb.append("    project:SetSetting('timelineOutputResolutionHeight', tostring(payload.h))\n");
        sb.append("    project:SetSetting('timelineFrameRate', tostring(payload.fps))\n");
        sb.append("    project:SetSetting('timelinePlaybackFrameRate', tostring(payload.fps))\n\n");

        sb.append("    local mediaPool = project:GetMediaPool()\n");
        sb.append("    if not mediaPool then print('[davinci] media pool unavailable') return end\n");
        sb.append("    local mediaStorage = resolve:GetMediaStorage()\n\n");

        sb.append("    -- 1. 逐个导入素材到媒体池（参照 AutoCutVideo 的 split_narration.lua 写法）\n");
        sb.append("    local byPath = {}\n");
        sb.append("    for _, mp in ipairs(payload.media_paths) do\n");
        sb.append("        local clips = mediaStorage:AddItemsToMediaPool(mp)\n");
        sb.append("        if clips and #clips > 0 then\n");
        sb.append("            byPath[mp] = clips[1]\n");
        sb.append("        else\n");
        sb.append("            print('[davinci] AddItemsToMediaPool failed: ' .. mp)\n");
        sb.append("        end\n");
        sb.append("    end\n\n");

        sb.append("    -- 2. 创建时间线 + 预先建好 A2/A3 音频轨（默认时间线只有 A1）\n");
        sb.append("    local timeline = mediaPool:CreateEmptyTimeline(payload.name)\n");
        sb.append("    if not timeline then print('[davinci] CreateEmptyTimeline failed') return end\n");
        sb.append("    timeline:SetSetting('useCustomSettings', '1')\n");
        sb.append("    timeline:SetSetting('timelineResolutionWidth', tostring(payload.w))\n");
        sb.append("    timeline:SetSetting('timelineResolutionHeight', tostring(payload.h))\n");
        sb.append("    timeline:SetSetting('timelineFrameRate', tostring(payload.fps))\n");
        sb.append("    -- 计算需要多少音频轨（A1 自动有；A2 给配音；A3 给 BGM）\n");
        sb.append("    local needA2 = false\n");
        sb.append("    for _, ch in ipairs(payload.chapters or {}) do\n");
        sb.append("        if ch.voiceover_path then needA2 = true; break end\n");
        sb.append("    end\n");
        sb.append("    local needA3 = (payload.bgm_path ~= nil)\n");
        sb.append("    if needA2 then\n");
        sb.append("        local ok = timeline:AddTrack('audio')\n");
        sb.append("        if not ok then print('[davinci] AddTrack A2 failed') end\n");
        sb.append("    end\n");
        sb.append("    if needA3 then\n");
        sb.append("        local ok = timeline:AddTrack('audio')\n");
        sb.append("        if not ok then print('[davinci] AddTrack A3 failed') end\n");
        sb.append("    end\n");
        sb.append("    print('[davinci] timeline tracks: video=' .. (timeline:GetTrackCount('video') or '?') ..\n");
        sb.append("        ', audio=' .. (timeline:GetTrackCount('audio') or '?'))\n");
        sb.append("    -- DaVinci 时间线起点不是 0，而是 timecode 01:00:00:00（30fps=108000 帧）。recordFrame 须用绝对帧。\n");
        sb.append("    local timelineStart = (timeline.GetStartFrame and timeline:GetStartFrame()) or 0\n");
        sb.append("    print('[davinci] timeline start frame=' .. tostring(timelineStart))\n\n");

        sb.append("    -- 3. 视频段：按源剪辑自身 fps 算 frame 号；不带 recordFrame，让 Resolve 顺序自动拼\n");
        sb.append("    local videoAppends = {}\n");
        sb.append("    local cursor_ms = 0\n");
        sb.append("    local chapterStarts_ms = {}\n");
        sb.append("    local anyStrip = false\n");
        sb.append("    for _, ch in ipairs(payload.chapters or {}) do\n");
        sb.append("        chapterStarts_ms[ch.id] = cursor_ms\n");
        sb.append("        if ch.strip_original_audio then anyStrip = true end\n");
        sb.append("        for _, pick in ipairs(ch.picks or {}) do\n");
        sb.append("            local item = byPath[pick.path]\n");
        sb.append("            if item then\n");
        sb.append("                local fpsStr = item:GetClipProperty('FPS')\n");
        sb.append("                local clipFps = tonumber(fpsStr) or payload.fps\n");
        sb.append("                local sf = math.floor(pick.start_ms * clipFps / 1000)\n");
        sb.append("                local ef = math.floor(pick.end_ms * clipFps / 1000)\n");
        sb.append("                if ef <= sf then ef = sf + 1 end\n");
        sb.append("                local entry = {\n");
        sb.append("                    mediaPoolItem = item,\n");
        sb.append("                    startFrame = sf,\n");
        sb.append("                    endFrame = ef,\n");
        sb.append("                }\n");
        sb.append("                table.insert(videoAppends, entry)\n");
        sb.append("                -- 模式 1 整体变速对齐配音：每段视频实际占据 timeline 时长 = origDur / speedFactor\n");
        sb.append("                local effectiveMs = pick.end_ms - pick.start_ms\n");
        sb.append("                if ch.speed_factor and ch.speed_factor > 0 then effectiveMs = effectiveMs / ch.speed_factor end\n");
        sb.append("                cursor_ms = cursor_ms + effectiveMs\n");
        sb.append("            else\n");
        sb.append("                print('[davinci] missing media for pick: ' .. tostring(pick.path))\n");
        sb.append("            end\n");
        sb.append("        end\n");
        sb.append("    end\n");
        sb.append("    if #videoAppends > 0 then\n");
        sb.append("        local r = mediaPool:AppendToTimeline(videoAppends)\n");
        sb.append("        if not r then print('[davinci] video AppendToTimeline failed') end\n");
        sb.append("    end\n");
        sb.append("    -- 模式 1（一个配音多个视频）：append 后给 V1 上每段视频按所属章节的 speed_factor 设倍速\n");
        sb.append("    do\n");
        sb.append("        local v1 = timeline:GetItemListInTrack('video', 1) or {}\n");
        sb.append("        local idx = 1\n");
        sb.append("        for _, ch in ipairs(payload.chapters or {}) do\n");
        sb.append("            local picksCount = #(ch.picks or {})\n");
        sb.append("            if ch.speed_factor and ch.speed_factor > 0 and math.abs(ch.speed_factor - 1.0) > 1e-6 then\n");
        sb.append("                local pct = ch.speed_factor * 100.0\n");
        sb.append("                for k = 1, picksCount do\n");
        sb.append("                    local it = v1[idx + k - 1]\n");
        sb.append("                    if it then\n");
        sb.append("                        local ok = pcall(function() it:SetClipProperty('Speed', tostring(pct)) end)\n");
        sb.append("                        if not ok then pcall(function() it:SetProperty('Speed', pct) end) end\n");
        sb.append("                    end\n");
        sb.append("                end\n");
        sb.append("                print('[davinci] chapter ' .. (ch.name or ch.id or '?') .. ' speed=' .. string.format('%.2f', pct) .. '%')\n");
        sb.append("            end\n");
        sb.append("            idx = idx + picksCount\n");
        sb.append("        end\n");
        sb.append("    end\n\n");

        sb.append("    -- 4. 「去除原音」：把 A1（视频自带音轨）整体静音\n");
        sb.append("    --    DaVinci 默认会把视频音轨 link 到 A1，我们把这些 A1 段 SetClipEnabled(false)\n");
        sb.append("    if anyStrip then\n");
        sb.append("        local a1items = timeline:GetItemListInTrack('audio', 1)\n");
        sb.append("        if a1items then\n");
        sb.append("            for _, ai in ipairs(a1items) do\n");
        sb.append("                local ok = pcall(function() ai:SetClipEnabled(false) end)\n");
        sb.append("                if not ok then\n");
        sb.append("                    pcall(function() ai:SetProperty('Volume', 0) end)\n");
        sb.append("                end\n");
        sb.append("            end\n");
        sb.append("            print('[davinci] muted ' .. #a1items .. ' clips on A1 (original video audio)')\n");
        sb.append("        end\n");
        sb.append("    end\n\n");

        sb.append("    -- 5. 章节配音：独占 A2，按章节累计 ms 转时间线 frame 定位\n");
        sb.append("    --    （音频没有意义上的源 fps，直接用项目 fps；GetClipProperty('FPS') 对 mp3 返回 0，会导致 endFrame=0）\n");
        sb.append("    local audioAppends = {}\n");
        sb.append("    for _, ch in ipairs(payload.chapters or {}) do\n");
        sb.append("        if ch.voiceover_path then\n");
        sb.append("            local voItem = byPath[ch.voiceover_path]\n");
        sb.append("            if voItem then\n");
        sb.append("                local voEnd = math.floor((ch.voiceover_dur_ms or 0) * payload.fps / 1000)\n");
        sb.append("                if voEnd > 0 then\n");
        sb.append("                    local startMs = chapterStarts_ms[ch.id] or 0\n");
        sb.append("                    local recordF = timelineStart + math.floor(startMs * payload.fps / 1000)\n");
        sb.append("                    table.insert(audioAppends, {\n");
        sb.append("                        mediaPoolItem = voItem,\n");
        sb.append("                        startFrame = 0,\n");
        sb.append("                        endFrame = voEnd,\n");
        sb.append("                        recordFrame = recordF,\n");
        sb.append("                        trackIndex = 2,\n");
        sb.append("                        mediaType = 2,\n");
        sb.append("                    })\n");
        sb.append("                end\n");
        sb.append("            end\n");
        sb.append("        end\n");
        sb.append("    end\n");
        sb.append("    if #audioAppends > 0 then\n");
        sb.append("        local r = mediaPool:AppendToTimeline(audioAppends)\n");
        sb.append("        local appended = (type(r) == 'table') and #r or (r and 1 or 0)\n");
        sb.append("        if not r or (type(r) == 'table' and #r == 0) then\n");
        sb.append("            print('[davinci] voiceover AppendToTimeline failed or returned empty (expected ' .. #audioAppends .. ')')\n");
        sb.append("        else\n");
        sb.append("            print('[davinci] voiceover appended: ' .. appended .. '/' .. #audioAppends)\n");
        sb.append("        end\n");
        sb.append("        -- 诊断：列出每条音频轨的 item，并打印其 timeline frame 区间\n");
        sb.append("        local audioCount = timeline:GetTrackCount('audio') or 0\n");
        sb.append("        for ti = 1, audioCount do\n");
        sb.append("            local items = timeline:GetItemListInTrack('audio', ti) or {}\n");
        sb.append("            print('[davinci] A' .. ti .. ' has ' .. #items .. ' items')\n");
        sb.append("            for _, it in ipairs(items) do\n");
        sb.append("                local nm = it.GetName and it:GetName() or '?'\n");
        sb.append("                local s = it.GetStart and it:GetStart() or -1\n");
        sb.append("                local e = it.GetEnd and it:GetEnd() or -1\n");
        sb.append("                local d = it.GetDuration and it:GetDuration() or -1\n");
        sb.append("                print('         · ' .. nm .. ' start=' .. tostring(s) .. ' end=' .. tostring(e) .. ' dur=' .. tostring(d))\n");
        sb.append("            end\n");
        sb.append("        end\n");
        sb.append("    end\n\n");

        sb.append("    -- 6. 全局 BGM：独占 A3 满轨（同样直接用项目 fps，避免 mp3 FPS=0 陷阱）\n");
        sb.append("    if payload.bgm_path and cursor_ms > 0 then\n");
        sb.append("        local bgmItem = byPath[payload.bgm_path]\n");
        sb.append("        if bgmItem then\n");
        sb.append("            local bgmEnd = math.floor(cursor_ms * payload.fps / 1000)\n");
        sb.append("            local r = mediaPool:AppendToTimeline({{\n");
        sb.append("                mediaPoolItem = bgmItem,\n");
        sb.append("                startFrame = 0,\n");
        sb.append("                endFrame = bgmEnd,\n");
        sb.append("                recordFrame = timelineStart,\n");
        sb.append("                trackIndex = 3,\n");
        sb.append("                mediaType = 2,\n");
        sb.append("            }})\n");
            sb.append("            local bgmAppended = (type(r) == 'table') and #r or (r and 1 or 0)\n");
        sb.append("            if not r or (type(r) == 'table' and #r == 0) then\n");
        sb.append("                print('[davinci] bgm AppendToTimeline failed or returned empty')\n");
        sb.append("            else\n");
        sb.append("                print('[davinci] bgm appended OK')\n");
        sb.append("            end\n");
        sb.append("        end\n");
        sb.append("    end\n");
        sb.append("    print('[davinci] timeline built: video=' .. #videoAppends ..\n");
        sb.append("        ', voiceovers=' .. #audioAppends ..\n");
        sb.append("        ', strip_audio=' .. tostring(anyStrip) ..\n");
        sb.append("        ', total_ms=' .. cursor_ms)\n\n");

        if (autoRender) {
            sb.append("    -- 4. 自动渲染（DIRECT 模式）\n");
            sb.append("    resolve:OpenPage('deliver')\n");
            sb.append("    if payload.codec == 'HEVC' then\n");
            sb.append("        project:LoadRenderPreset('H.265 Master')\n");
            sb.append("    else\n");
            sb.append("        project:LoadRenderPreset('H.264 Master')\n");
            sb.append("    end\n");
            sb.append("    project:SetCurrentRenderFormatAndCodec(payload.format, payload.encoder)\n");
            sb.append("    project:SetRenderSettings({ TargetDir = payload.output_dir })\n");
            sb.append("    local jobId = project:AddRenderJob()\n");
            sb.append("    if jobId and jobId ~= '' then\n");
            sb.append("        project:StartRendering({ jobId })\n");
            sb.append("        print('[davinci] render started: jobId=' .. jobId)\n");
            sb.append("    else\n");
            sb.append("        print('[davinci] AddRenderJob failed')\n");
            sb.append("    end\n");
        } else {
            sb.append("    -- PREVIEW_EDIT 模式：仅装配时间线，不进入渲染队列。完成后请手工调整并导出。\n");
            sb.append("    print('[davinci] timeline ready for manual editing; not rendering automatically')\n");
        }

        sb.append("end\n\n");
        sb.append("run()\n");
        return sb.toString();
    }

    private String absLua(Args args) {
        return args.parentDir.resolve(sanitize(args.name)).resolve("main.lua").toAbsolutePath().toString();
    }

    /** 序列化 payload 为 Lua table 字面量 */
    private String luaTablePayload(Args args, Map<String, Path> resourceAssetMap, int fps) {
        StringBuilder sb = new StringBuilder("{\n");
        sb.append("    name = ").append(luaStr(args.name)).append(",\n");
        sb.append("    w = ").append(args.canvasW).append(",\n");
        sb.append("    h = ").append(args.canvasH).append(",\n");
        sb.append("    fps = ").append(fps).append(",\n");
        sb.append("    codec = ").append(luaStr(args.codec == null ? "H264" : args.codec)).append(",\n");
        sb.append("    encoder = ").append(luaStr("H264".equalsIgnoreCase(args.codec) ? "H264" : "H265")).append(",\n");
        sb.append("    format = ").append(luaStr("MOV".equalsIgnoreCase(args.container) ? "mov" : "mp4")).append(",\n");
        sb.append("    output_dir = ").append(luaStr(args.renderOutputDir == null ? "" : args.renderOutputDir.toAbsolutePath().toString())).append(",\n");

        // media_paths
        Set<String> uniquePaths = new java.util.LinkedHashSet<>();
        for (Path p : resourceAssetMap.values()) uniquePaths.add(p.toAbsolutePath().toString());
        sb.append("    media_paths = {\n");
        for (String p : uniquePaths) {
            sb.append("        ").append(luaStr(p)).append(",\n");
        }
        sb.append("    },\n");

        // chapters
        sb.append("    chapters = {\n");
        if (args.plan.getChapters() != null) {
            for (ChapterPlan ch : args.plan.getChapters()) {
                sb.append("        {\n");
                sb.append("            id = ").append(ch.getChapterId()).append(",\n");
                sb.append("            name = ").append(luaStr(ch.getChapterName())).append(",\n");
                sb.append("            strip_original_audio = ").append(Boolean.TRUE.equals(ch.getStripOriginalAudio())).append(",\n");
                if (ch.getSpeedFactor() != null && Math.abs(ch.getSpeedFactor() - 1.0) > 1e-6) {
                    sb.append("            speed_factor = ").append(String.format("%.6f", ch.getSpeedFactor())).append(",\n");
                }
                if (ch.getVoiceoverOssKey() != null) {
                    Path vo = resourceAssetMap.get(ch.getVoiceoverOssKey());
                    if (vo != null) {
                        sb.append("            voiceover_path = ").append(luaStr(vo.toAbsolutePath().toString())).append(",\n");
                        sb.append("            voiceover_dur_ms = ").append(ch.getVoiceoverDurationMs() == null ? 0 : ch.getVoiceoverDurationMs()).append(",\n");
                    }
                }
                sb.append("            picks = {\n");
                if (ch.getPicks() != null) {
                    for (ClipPick p : ch.getPicks()) {
                        Path resPath = resourceAssetMap.get(p.getOssKey());
                        if (resPath == null) continue;
                        sb.append("                { path = ").append(luaStr(resPath.toAbsolutePath().toString()))
                          .append(", start_ms = ").append(p.getStartMs() == null ? 0 : p.getStartMs())
                          .append(", end_ms = ").append(p.getEndMs() == null ? 0 : p.getEndMs())
                          .append(" },\n");
                    }
                }
                sb.append("            },\n");
                sb.append("        },\n");
            }
        }
        sb.append("    },\n");

        // bgm
        if (args.plan.getGlobalBgmOssKey() != null) {
            Path bgm = resourceAssetMap.get(args.plan.getGlobalBgmOssKey());
            if (bgm != null) {
                sb.append("    bgm_path = ").append(luaStr(bgm.toAbsolutePath().toString())).append(",\n");
            }
        }

        sb.append("}");
        return sb.toString();
    }

    private static String luaStr(String s) {
        if (s == null) return "nil";
        // Lua 字符串转义：单引号 / 反斜杠 / 换行
        return "'" + s.replace("\\", "\\\\").replace("'", "\\'").replace("\n", "\\n").replace("\r", "\\r") + "'";
    }

    /**
     * 内嵌 getResolve()：兼容 DaVinci Resolve 各版本各执行环境。
     * - Console (Lua tab) 的全局 Resolve 通常就是 userdata 本身
     * - 部分版本是函数 Resolve()
     * - Fusion 嵌入式 app:GetResolve()/fusion:GetResolve()
     * - bmd.scriptapp('Resolve')
     * 全部失败时打印诊断信息，便于反馈实际环境。
     */
    private static final String LUA_GET_RESOLVE = ""
            + "local function getResolve()\n"
            + "    -- 1) 全局 Resolve 直接是对象（最常见，DaVinci 18+ Console）\n"
            + "    if Resolve ~= nil and type(Resolve) ~= 'function' then return Resolve end\n"
            + "    -- 2) Resolve 是函数（部分版本）\n"
            + "    if type(Resolve) == 'function' then\n"
            + "        local ok, r = pcall(Resolve)\n"
            + "        if ok and r then return r end\n"
            + "    end\n"
            + "    -- 3) Fusion 嵌入式：app:GetResolve()\n"
            + "    if app ~= nil and type(app) == 'table' and type(app.GetResolve) == 'function' then\n"
            + "        local ok, r = pcall(app.GetResolve, app)\n"
            + "        if ok and r then return r end\n"
            + "    end\n"
            + "    if app ~= nil and type(app) == 'userdata' then\n"
            + "        local ok, r = pcall(function() return app:GetResolve() end)\n"
            + "        if ok and r then return r end\n"
            + "    end\n"
            + "    -- 4) fusion:GetResolve()\n"
            + "    if fusion ~= nil and type(fusion.GetResolve) == 'function' then\n"
            + "        local ok, r = pcall(function() return fusion:GetResolve() end)\n"
            + "        if ok and r then return r end\n"
            + "    end\n"
            + "    -- 5) bmd.scriptapp('Resolve')\n"
            + "    if bmd ~= nil and type(bmd.scriptapp) == 'function' then\n"
            + "        local ok, r = pcall(bmd.scriptapp, 'Resolve')\n"
            + "        if ok and r then return r end\n"
            + "    end\n"
            + "    return nil\n"
            + "end\n"
            + "\n"
            + "local function diagnose()\n"
            + "    print('[davinci] diagnostic:')\n"
            + "    print('  Resolve type=' .. type(Resolve))\n"
            + "    print('  app type=' .. type(app))\n"
            + "    print('  fusion type=' .. type(fusion))\n"
            + "    print('  bmd type=' .. type(bmd))\n"
            + "    print('请把上面 4 行截图反馈')\n"
            + "end\n";

    // ─────────────────── 素材拷贝 + 友好命名 ───────────────────

    private Map<String, Path> copyAssetsToResources(Map<String, Path> assetMap, Path resourcesDir,
                                                     Map<String, String> friendlyNames) throws IOException {
        Map<String, Path> resourceMap = new LinkedHashMap<>();
        Map<Path, Path> srcToDst = new HashMap<>();
        Set<String> usedNames = new HashSet<>();
        for (Map.Entry<String, Path> e : assetMap.entrySet()) {
            String ossKey = e.getKey();
            Path src = e.getValue();
            if (src == null || !Files.exists(src)) continue;
            Path dst = srcToDst.get(src);
            if (dst == null) {
                String preferred = friendlyNames.get(ossKey);
                String fallback = src.getFileName().toString();
                String desired = (preferred != null && !preferred.isBlank()) ? preferred : fallback;
                if (preferred != null && !preferred.contains(".")) {
                    String ext = extOf(fallback);
                    if (ext.isEmpty()) ext = extOf(ossKey);
                    if (!ext.isEmpty()) desired = preferred + ext;
                }
                String name = uniqueName(desired, usedNames);
                dst = resourcesDir.resolve(name);
                Files.copy(src, dst, StandardCopyOption.REPLACE_EXISTING);
                srcToDst.put(src, dst);
                usedNames.add(name);
            }
            resourceMap.put(ossKey, dst);
        }
        return resourceMap;
    }

    private Map<String, String> collectFriendlyNames(CompositionPlan plan) {
        Map<String, String> names = new HashMap<>();
        if (plan.getChapters() != null) {
            for (ChapterPlan ch : plan.getChapters()) {
                if (ch.getPicks() != null) {
                    for (ClipPick p : ch.getPicks()) {
                        if (p.getOssKey() != null && p.getOriginalName() != null && !p.getOriginalName().isBlank()) {
                            names.putIfAbsent(p.getOssKey(), p.getOriginalName());
                        }
                    }
                }
                if (ch.getVoiceoverOssKey() != null) {
                    names.putIfAbsent(ch.getVoiceoverOssKey(), "voiceover_" + ch.getChapterId());
                }
            }
        }
        if (plan.getGlobalBgmOssKey() != null) {
            names.putIfAbsent(plan.getGlobalBgmOssKey(), "bgm");
        }
        return names;
    }

    private static String uniqueName(String original, Set<String> used) {
        String safe = sanitize(original);
        if (!used.contains(safe)) return safe;
        int dot = safe.lastIndexOf('.');
        String base = dot > 0 ? safe.substring(0, dot) : safe;
        String ext = dot > 0 ? safe.substring(dot) : "";
        for (int i = 2; i < 1000; i++) {
            String candidate = base + "_" + i + ext;
            if (!used.contains(candidate)) return candidate;
        }
        return safe + "_" + UUID.randomUUID().toString().substring(0, 6) + ext;
    }

    private static String extOf(String s) {
        if (s == null) return "";
        int dot = s.lastIndexOf('.');
        if (dot <= 0 || dot == s.length() - 1) return "";
        String tail = s.substring(dot);
        return tail.length() > 6 ? "" : tail.toLowerCase();
    }

    private static String sanitize(String name) {
        if (name == null || name.isBlank()) return UUID.randomUUID().toString();
        return name.replaceAll("[/\\\\:*?\"<>|]", "_");
    }

    private static int countPicks(CompositionPlan plan) {
        int n = 0;
        if (plan.getChapters() != null) {
            for (ChapterPlan ch : plan.getChapters()) {
                if (ch.getPicks() != null) n += ch.getPicks().size();
            }
        }
        return n;
    }
}
