CREATE TABLE IF NOT EXISTS script_blueprint
(
    id                          BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nezha_tenant_code           VARCHAR(64)  NULL,
    is_deleted                  TINYINT(1)   NOT NULL DEFAULT 0,
    blueprint_code              VARCHAR(64)  NOT NULL COMMENT '蓝图编码',
    sku_id                      VARCHAR(128) NOT NULL COMMENT '标准SKU ID',
    category_code               VARCHAR(64)  NULL COMMENT '品类编码',
    marketing_goal              VARCHAR(64)  NOT NULL COMMENT '营销目标',
    marketing_node              VARCHAR(64)  NULL COMMENT '营销节点',
    target_audience             VARCHAR(256) NULL COMMENT '目标人群',
    platform                    VARCHAR(64)  NULL COMMENT '平台',
    account_id                  VARCHAR(128) NULL COMMENT '账号ID',
    status                      VARCHAR(32)  NULL DEFAULT 'DRAFT',
    blueprint_summary           VARCHAR(1024) NULL COMMENT '蓝图摘要',
    recommended_template_code   VARCHAR(128) NULL COMMENT '推荐模板编码',
    recommended_template_name   VARCHAR(256) NULL COMMENT '推荐模板名称',
    recommended_template_reason VARCHAR(1024) NULL COMMENT '推荐模板理由',
    template_candidates_json    JSON         NULL COMMENT '候选模板JSON',
    blueprint_json              JSON         NULL COMMENT '蓝图JSON',
    logic_trace                 JSON         NULL COMMENT '逻辑追踪JSON',
    auto_flow_status            VARCHAR(64)  NULL COMMENT '自动流转状态',
    create_at                   DATETIME     NULL,
    create_by                   BIGINT       NULL,
    create_name                 VARCHAR(255) NULL,
    update_at                   DATETIME     NULL,
    update_by                   BIGINT       NULL,
    update_name                 VARCHAR(255) NULL,
    UNIQUE INDEX uk_blueprint_code (blueprint_code),
    INDEX idx_sku_goal (sku_id, marketing_goal)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '语义蓝图主表';

CREATE TABLE IF NOT EXISTS script_blueprint_section
(
    id                      BIGINT       NOT NULL AUTO_INCREMENT PRIMARY KEY,
    nezha_tenant_code       VARCHAR(64)  NULL,
    is_deleted              TINYINT(1)   NOT NULL DEFAULT 0,
    blueprint_code          VARCHAR(64)  NOT NULL COMMENT '蓝图编码',
    section_no              INT          NOT NULL COMMENT '段落序号',
    stage_code              VARCHAR(64)  NOT NULL COMMENT '阶段编码',
    stage_name              VARCHAR(128) NULL COMMENT '阶段名称',
    goal                    VARCHAR(512) NULL COMMENT '段落目标',
    semantic_intent         VARCHAR(1024) NULL COMMENT '语义意图',
    query_text              VARCHAR(1024) NULL COMMENT '检索文本',
    must_cover_json         JSON         NULL COMMENT '必须覆盖点',
    preferred_signals_json  JSON         NULL COMMENT '偏好信号',
    avoid_signals_json      JSON         NULL COMMENT '避免信号',
    duration_min            INT          NULL COMMENT '最小时长',
    duration_max            INT          NULL COMMENT '最大时长',
    narration_hint          VARCHAR(1024) NULL COMMENT '口播提示',
    create_at               DATETIME     NULL,
    create_by               BIGINT       NULL,
    create_name             VARCHAR(255) NULL,
    update_at               DATETIME     NULL,
    update_by               BIGINT       NULL,
    update_name             VARCHAR(255) NULL,
    INDEX idx_blueprint_code (blueprint_code),
    INDEX idx_stage_code (stage_code)
) ENGINE = InnoDB DEFAULT CHARSET = utf8mb4 COMMENT = '语义蓝图段落表';
