-- 视频最小单元（片段级拆解结果），与飞书「最小单元库」字段对齐
CREATE TABLE IF NOT EXISTS video_segment (
    id                   BIGINT        NOT NULL AUTO_INCREMENT COMMENT '主键',
    task_id              VARCHAR(64)   NOT NULL COMMENT '来源任务ID（video_task_xxx）',
    video_id             VARCHAR(64)   NOT NULL COMMENT '视频ID（来自 video_deconstruction_result）',
    sku_id               VARCHAR(64)   NOT NULL COMMENT 'SKU ID',
    segment_index        INT           NOT NULL DEFAULT 0 COMMENT '片段序号（从1开始）',
    start_sec            INT           NOT NULL DEFAULT 0 COMMENT '开始秒',
    end_sec              INT           NOT NULL DEFAULT 0 COMMENT '结束秒',
    structure_tag        VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '结构标签（钩子/功效可视化/妆效展示/CTA收尾...）',
    motivation           VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '动机（痛点/卖点/拉踩点/转化点...）',
    technique            VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '手法（情绪渲染/功效描述/对比实证...）',
    camera_language      VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '镜头语言（特写/全景/POV...）',
    scene                VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '场景（浴室/梳妆台/户外...）',
    signal_strength      INT           NOT NULL DEFAULT 0 COMMENT '信号强度 1-5',
    key_phrase           VARCHAR(256)  NOT NULL DEFAULT '' COMMENT '金句（关键词用|分隔）',
    script               TEXT                   COMMENT '对应话术',
    selling_point        VARCHAR(256)  NOT NULL DEFAULT '' COMMENT '卖点内容',
    is_decisive_frame    TINYINT       NOT NULL DEFAULT 0 COMMENT '是否决定性画面',
    decisive_frame_desc  VARCHAR(256)  NOT NULL DEFAULT '' COMMENT '决定性画面描述',
    influencer_level     VARCHAR(16)   NOT NULL DEFAULT '' COMMENT '人物量级（模特/无人物/明星/素人/KOC）',
    audience_persona     VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '人物画像（精致妈妈/新锐白领/Z世代...）',
    bgm                  VARCHAR(16)   NOT NULL DEFAULT '' COMMENT 'BGM（无/轻快/ASMR/热门曲...）',
    rhythm               VARCHAR(16)   NOT NULL DEFAULT '' COMMENT '节奏（快剪/中速/慢推...）',
    wardrobe             VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '服化道',
    audio                VARCHAR(16)   NOT NULL DEFAULT '' COMMENT '声音（达人原声/专业旁白/无人声）',
    skin_type            VARCHAR(32)   NOT NULL DEFAULT '' COMMENT '肤质肤况',
    trending             VARCHAR(128)  NOT NULL DEFAULT '' COMMENT '热点关键词',
    verification_status  VARCHAR(16)   NOT NULL DEFAULT 'TEMP' COMMENT '验证状态（TEMP/VERIFIED/REJECTED）',
    nezha_tenant_code    VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '租户编码',
    create_at            DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
    create_by            BIGINT        NOT NULL DEFAULT 0 COMMENT '创建人ID',
    create_name          VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '创建人名称',
    update_at            DATETIME      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
    update_by            BIGINT        NOT NULL DEFAULT 0 COMMENT '更新人ID',
    update_name          VARCHAR(64)   NOT NULL DEFAULT '' COMMENT '更新人名称',
    is_deleted           TINYINT       NOT NULL DEFAULT 0 COMMENT '软删除（0正常 1删除）',
    PRIMARY KEY (id),
    INDEX idx_task_id (task_id),
    INDEX idx_video_id (video_id),
    INDEX idx_sku_id (sku_id),
    INDEX idx_structure_tag (structure_tag),
    INDEX idx_signal_strength (signal_strength)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='视频最小单元库（片段级拆解）';
